using Purview.DotNetProjectSdk.Harness;

namespace Purview.DotNetProjectSdk.Tests;

/// <summary>
/// Verifies SDK properties are exported as CompilerVisibleProperty items so Roslyn
/// analyzers/source generators can consume them via build_property.*.
/// </summary>
public sealed class CompilerVisiblePropertyTests
{
	[Test]
	public async Task CompilerVisibleProperties_Include_AllSdkProperties(
		CancellationToken cancellationToken
	)
	{
		using var h = await ProjectHarness.CreateAsync(
			"MyLibrary",
			cancellationToken: cancellationToken
		);
		var compilerVisibleProperties = await h.GetItemIdentitiesAsync(
			"CompilerVisibleProperty",
			cancellationToken
		);

		var expected = new[]
		{
			"UsePackageJsonVersion",
			"RootPackageJson",
			"RepoRoot",
			"Version",
			"PackageVersion",
			"NamespacePrefix",
			"DisableNamespacePrefixCheck",
			"TestingFramework",
			"SubstituteFramework",
			"TestDataFramework",
			"SourceLinkPackageName",
			"ExcludePurviewTelemetry",
			"ExcludeMSTelemetryExtension",
			"DisableGenerateAssemblyInfoClass",
			"EnableAssemblyNameGeneration",
			"DisableAutoInternalsVisibleTo",
			"AutoIncludeUsings",
			"IsCSharpProject",
			"IsTestProject",
			"IsSharedTestingProject",
			"TestingType",
			"TargetProjectName",
			"IsContainerProject",
			"IsSdkProject",
			"SdkProjectName",
			"IsWebProject",
			"IsWebSdkProject",
			"IsWorkerSdkProject",
			"IsAspireHostProject",
			"EditorConfigFilePath",
			"CurrentYear",
			"AutoGeneratedAssemblyInfoFile",
		};

		foreach (var propertyName in expected)
			await Assert.That(compilerVisibleProperties).Contains(propertyName);
	}
}
